/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class app_sand_throughputtest_MemoryRWJni */

#ifndef _Included_app_sand_throughputtest_MemoryRWJni
#define _Included_app_sand_throughputtest_MemoryRWJni
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     app_sand_throughputtest_MemoryRWJni
 * Method:    MemoryReadRate
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_app_sand_throughputtest_MemoryRWJni_MemoryReadRate
  (JNIEnv *, jobject, jlong);

/*
 * Class:     app_sand_throughputtest_MemoryRWJni
 * Method:    MemoryWriteRate
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_app_sand_throughputtest_MemoryRWJni_MemoryWriteRate
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
